/* =====================================================
   FEATURE 1: Topic Explainer
   ===================================================== */

function initExplainer() {
  const input  = document.getElementById('explainer-input');
  const btn    = document.getElementById('explainer-btn');
  const mic    = document.getElementById('explainer-mic');
  const load   = document.getElementById('explainer-loading');
  const msg    = document.getElementById('loading-msg');
  const results= document.getElementById('explainer-results');
  const cls    = document.getElementById('explainer-class');
  const board  = document.getElementById('explainer-board');

  if (!btn) return;

  btn.addEventListener('click', () => runExplainer());

  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) runExplainer();
  });

  // Voice input
  attachVoiceInput(mic, input, 'explainer');

  async function runExplainer() {
    const topic = input.value.trim();
    if (!topic) {
      showToast('Please enter a topic first! / पहले topic likhein!');
      return;
    }

    // Show loading
    results.innerHTML = '';
    load.classList.remove('hidden');
    btn.disabled = true;
    const interval = startLoadingMessages('loading-msg');

    try {
      const prompt = buildExplainerPrompt(topic, cls.value, board.value);
      const response = await callGemini(prompt, 0.7, 2500);

      // Track in stats
      trackStat('topics_studied');
      cacheLastResponse('explainer', { topic, response });

      load.classList.add('hidden');
      stopLoadingMessages(interval);
      results.innerHTML = renderExplainerResponse(topic, response);
      results.scrollIntoView({ behavior: 'smooth', block: 'start' });
      initReadAloud(results);
      initCopyButtons(results);
    } catch (err) {
      load.classList.add('hidden');
      stopLoadingMessages(interval);
      results.innerHTML = buildErrorCard(err.message);
      document.getElementById('retry-btn')?.addEventListener('click', runExplainer);
    } finally {
      btn.disabled = false;
    }
  }
}

// ── Render explainer response ────────────────────────────
function renderExplainerResponse(topic, rawText) {
  const sections = parseExplainerSections(rawText);

  return `
    <div class="results-container fade-in">
      <div class="result-topic-header">
        <h2 style="color:var(--navy);font-size:20px;font-weight:700;margin-bottom:4px;">📖 ${escHTML(topic)}</h2>
        <p style="color:var(--text-muted);font-size:13px;">Complete study guide generated by AI Study Buddy</p>
      </div>

      ${renderSection('A', '💡', 'Simple Explanation', 'सरल समझाइए', sections.sectionA)}
      ${renderSection('B', '📖', 'Key Terms Glossary', 'महत्वाचे शब्द', sections.sectionB, 'glossary')}
      ${renderSection('C', '🧠', 'Memory Tricks', 'याद करने की तरकीब', sections.sectionC, 'memory')}
      ${renderSection('D', '📝', 'Practice Questions', 'अभ्यास प्रश्न', sections.sectionD, 'questions')}
      ${renderSection('E', '🎯', 'Exam Tips', 'परीक्षा टिप्स', sections.sectionE, 'tips')}
      ${sections.encourage ? renderEncourageBox(sections.encourage) : ''}
    </div>
  `;
}

function parseExplainerSections(text) {
  const sA = extractSection(text, 'SECTION A');
  const sB = extractSection(text, 'SECTION B');
  const sC = extractSection(text, 'SECTION C');
  const sD = extractSection(text, 'SECTION D');
  const sE = extractSection(text, 'SECTION E');
  const enc = extractSection(text, 'ENCOURAGING MESSAGE');

  return {
    sectionA: sA || extractFallback(text, 0),
    sectionB: sB || '',
    sectionC: sC || '',
    sectionD: sD || '',
    sectionE: sE || '',
    encourage: enc || ''
  };
}

function extractSection(text, sectionName) {
  const regex = new RegExp(`##?\\s*${sectionName}[^\\n]*\\n([\\s\\S]*?)(?=##?\\s*SECTION|##?\\s*ENCOURAGING|$)`, 'i');
  const match = text.match(regex);
  return match ? match[1].trim() : null;
}

function extractFallback(text, start) {
  return text.substring(start, 400).trim();
}

function renderSection(letter, icon, titleEn, titleHi, content, type = 'text') {
  if (!content) return '';

  let bodyHtml = '';

  if (type === 'memory') {
    bodyHtml = `<div class="memory-box">
      <div class="memory-box-title">🧠 Memory Trick</div>
      ${markdownToHtml(content)}
    </div>`;
  } else if (type === 'tips') {
    const tips = content.split(/\d+\.\s+/).filter(t => t.trim());
    bodyHtml = tips.map((tip, i) => `
      <div class="exam-tip">
        <div class="exam-tip-num">${i + 1}</div>
        <div>${markdownToHtml(tip)}</div>
      </div>`).join('');
    if (!bodyHtml) bodyHtml = `<div class="ai-card-body">${markdownToHtml(content)}</div>`;
  } else {
    bodyHtml = `<div class="ai-card-body">${markdownToHtml(content)}</div>`;
  }

  return `
    <div class="ai-card fade-in">
      <div class="ai-card-header">
        <span class="ai-card-icon">${icon}</span>
        <div>
          <div class="ai-card-title">Section ${letter} — ${titleEn}</div>
          <div style="font-size:12px;color:var(--text-muted)">${titleHi}</div>
        </div>
      </div>
      ${bodyHtml}
      <div class="ai-card-footer">
        <button class="action-chip read-aloud-btn" data-target="section-${letter}">🔊 Read Aloud</button>
        <button class="action-chip copy-btn" data-target="section-${letter}">📋 Copy</button>
      </div>
      <div id="section-${letter}-content" style="display:none">${content}</div>
    </div>`;
}

function renderEncourageBox(text) {
  return `
    <div class="ai-card fade-in" style="border-left-color:var(--green);background:linear-gradient(135deg,var(--success-light),#fff)">
      <div class="ai-card-header">
        <span class="ai-card-icon">🌟</span>
        <div class="ai-card-title">तुम्ही हे करू शकता! / You Can Do This!</div>
      </div>
      <div class="ai-card-body" style="font-size:16px;font-weight:500;color:var(--green-dark)">
        ${markdownToHtml(text)}
      </div>
    </div>`;
}

// ── Read aloud & copy helper ─────────────────────────────
function initReadAloud(container) {
  container.querySelectorAll('.read-aloud-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.dataset.target;
      const contentEl = document.getElementById(`${target}-content`);
      const text = contentEl ? contentEl.textContent : '';
      if (text) speakText(text.substring(0, 1000));
    });
  });
}

function initCopyButtons(container) {
  container.querySelectorAll('.copy-btn').forEach(btn => {
    btn.addEventListener('click', async () => {
      const target = btn.dataset.target;
      const contentEl = document.getElementById(`${target}-content`);
      const text = contentEl ? contentEl.textContent : '';
      if (text) {
        await navigator.clipboard.writeText(text).catch(() => {});
        btn.textContent = '✅ Copied!';
        btn.classList.add('copied');
        setTimeout(() => {
          btn.textContent = '📋 Copy';
          btn.classList.remove('copied');
        }, 2000);
      }
    });
  });
}
